version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: npm run build
      - jest/test:
          steps:
            - checkout
            - run: npm run test
          requires:
            - cypress/install
      - cypress/run:
          requires:
            - cypress/install
